# Import library

In [1]:
import pandas as pd
import re
import numpy as np

#library that contains punctuation
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

# Import data

In [2]:
df=pd.read_csv('alonhadat.csv')

In [3]:
df.columns

Index(['post_id', 'Loại tin', 'Tiêu đề', 'Mô tả', 'Giá:', 'Diện tích:',
       'Địa chỉ', 'Mã tin', 'Hướng', 'Phòng ăn', 'Đường trước nhà', 'Nhà bếp',
       'Loại BDS', 'Pháp lý', 'Sân thượng', 'Chiều ngang', 'Số lầu',
       'Chổ để xe hơi', 'Chiều dài', 'Số phòng ngủ', 'Chính chủ', 'URL',
       'date', 'Liên hệ', 'phone', 'Thuộc dự án'],
      dtype='object')

In [4]:
df.head()

post_id Loại tin                                            Tiêu đề  \
0  13131558  Cần bán  Bán Nhà Đẹp VIEW Biển NGUYỄN TẤT THÀNH 4 Tầng ...   
1  13456587  Cần bán  Góc 3 Mặt Tiền Nguyễn Phong Sắc 3 Đường 7m5 VỊ...   
2  13467139  Cần bán   BÁN BIỆT THỰ SÂN VƯỜN 150M2 KIỆT TÔ HIỆU lh Hiền   
3  12734876  Cần bán  Bán khách sạn 2mt Đống Đa, Lý Tự Trọng, dtd: 2...   
4  13472701  Cần bán  Lê Thị Xuyến đường 5m5 Dt= 63m2 kẹp kiệt 2 tần...   

                                               Mô tả      Giá: Diện tích:  \
0  Nhà đẹp, view biển, 4 tầng, 9 phòng ngủ, khu v...  11,45 tỷ     125 m2   
1  + Bán lô góc 3 mặt tiền 3 đường 7m5 Nguyễn Pho...  9,999 tỷ     160 m2   
2  🌺🌺Nhà sân vườn biệt thự 3 tầng mới xây, đường ...   3,25 tỷ     150 m2   
3  Bán toà nhà khách sạn hai mặt tiền Đống Đa,Lý ...     72 tỷ   2.300 m2   
4  Hàng hiếm.Lê Thị Xuyến đường 5m5 Dt= 63m2 kẹp ...    4,7 tỷ      63 m2   

                                             Địa chỉ    Mã tin    Hướng  \
0  Địa chỉ tài sản: Đường Nguyễn Tất Thành, Phườn...  13131558        _   
1  Địa chỉ tài sản: Đường Nguyễn Phong Sắc, Phườn...  13456587        _   
2  Địa chỉ tài sản: Đường Tô Hiệu, Phường Hòa Min...  13467139        _   
3  Địa chỉ tài sản: 191 Đường Đống Đa, Phường Thạ...  12734876  Tây Nam   
4  Địa chỉ tài sản: Đường Lê Thị Xuyến, Phường Xu...  13472701      Bắc   

  Phòng ăn  ... Số lầu Chổ để xe hơi Chiều dài Số phòng ngủ Chính chủ  \
0      NaN  ...      4           NaN       25m            9       ---   
1      NaN  ...      1           NaN       18m            1       ---   
2      NaN  ...      3           ---       ---            3       ---   
3      ---  ...     10           ---       24m           50       ---   
4      NaN  ...      2           NaN       16m            3       ---   

                                                 URL        date  \
0  https://alonhadat.com.vn//ban-nha-dep-view-bie...  2023-10-02   
1  https://alonhadat.com.vn//ban-lo-goc-3-mat-tie...  2023-10-02   
2  https://alonhadat.com.vn//ban-biet-thu-san-vuo...  2023-10-02   
3  https://alonhadat.com.vn//ban-toa-nha-2mt-dong...  2023-10-02   
4  https://alonhadat.com.vn//le-thi-xuyen-duong-5...  2023-10-02   

          Liên hệ                          phone Thuộc dự án  
0  Trần Trung Hậu  0702.446.393  /  0931.949.123         NaN  
1  Trần Trung Hậu  0702.446.393  /  0931.949.123         NaN  
2       Hiền Hiền  0777.363.036  /  0905.269.343         NaN  
3            Quốc                   0903.548.978         NaN  
4       Nguyễn Ái                   0935.282.118         NaN  

[5 rows x 26 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8042 entries, 0 to 8041
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   post_id          8042 non-null   int64 
 1   Loại tin         8042 non-null   object
 2   Tiêu đề          8042 non-null   object
 3   Mô tả            8042 non-null   object
 4   Giá:             8042 non-null   object
 5   Diện tích:       8042 non-null   object
 6   Địa chỉ          8042 non-null   object
 7   Mã tin           8042 non-null   int64 
 8   Hướng            8042 non-null   object
 9   Phòng ăn         4127 non-null   object
 10  Đường trước nhà  8042 non-null   object
 11  Nhà bếp          4118 non-null   object
 12  Loại BDS         8042 non-null   object
 13  Pháp lý          8042 non-null   object
 14  Sân thượng       4395 non-null   object
 15  Chiều ngang      8042 non-null   object
 16  Số lầu           8042 non-null   object
 17  Chổ để xe hơi    4138 non-null   

In [6]:
df.shape

(8042, 26)

# Function

In [7]:
def replace_empty_with_nan(text):
    return np.nan if text.strip() == '' else text

# Loại tin

In [8]:
df['Loại tin'].unique()

array(['Cần bán'], dtype=object)

In [9]:
df['Loại tin']=df['Loại tin'].replace('Cần bán','Mua bán')

# Diện tích

In [10]:
# df['Diện tích:'].unique()

In [11]:
def clean_size(i):
    if isinstance(i, str):
        # Remove ' m²', periods, and replace 'KXĐ' with an empty string
        return i.replace(' m2', '').replace('.', '').replace('KXĐ', '')
    else:
        return ''

In [12]:
df['Diện tích:'] = df['Diện tích:'].apply(clean_size)

In [13]:
df['Diện tích:'] = df['Diện tích:'].apply(replace_empty_with_nan)

In [14]:
df['Diện tích:']=df['Diện tích:'].astype(float)

# Giá 

In [15]:
# df['Giá:'].unique()

In [16]:
df['Giá:'][df['Loại tin']=='Mua bán'].unique()

array(['11,45 tỷ', '9,999 tỷ', '3,25 tỷ', '72 tỷ', '4,7 tỷ', '2,25 tỷ',
       '3 tỷ', '28 tỷ', '15,8 tỷ', '6 tỷ', '5,95 tỷ', '3,79 tỷ',
       '18,5 tỷ', '2,75 tỷ', '10,8 tỷ', '6,6 tỷ', '8,8 tỷ', '26 tỷ',
       '3,3 tỷ', '15 tỷ', 'Thỏa thuận', '12 tỷ', '3,35 tỷ', '14,48 tỷ',
       '3,55 tỷ', '3,68 tỷ', '4,15 tỷ', '10,5 tỷ', '6,5 tỷ', '999 tỷ',
       '5,35 tỷ', '4,25 tỷ', '3,4 tỷ', '3,29 tỷ', '4,19 tỷ', '800 triệu',
       '13,4 tỷ', '45 tỷ', '95 tỷ', '19,25 tỷ', '4,45 tỷ', '3,7 tỷ',
       '16 tỷ', '5,4 tỷ', '4,99 tỷ', '2 tỷ', '580 tỷ', '6,8 tỷ', '320 tỷ',
       '77 tỷ', '20 tỷ', '24,5 tỷ', '8,4 tỷ', '8,2 tỷ', '4,95 tỷ',
       '3,2 tỷ', '5,3 tỷ', '5,5 tỷ', '10 tỷ', '6,7 tỷ', '7,65 tỷ',
       '1,4 tỷ', '17,5 tỷ', '7,7 tỷ', '14,5 tỷ', '16,8 tỷ', '7 tỷ',
       '6,9 tỷ', '28,8 tỷ', '8,5 tỷ', '5,8 tỷ', '12,3 tỷ', '15,5 tỷ',
       '3,6 tỷ', '4,5 tỷ', '3,1 tỷ', '2,55 tỷ', '10,4 tỷ', '10,9 tỷ',
       '22 tỷ', '6,2 tỷ', '17 tỷ', '27,5 tỷ', '2,3 tỷ', '11,5 tỷ',
       '30 triệu /\xa0m2

In [17]:
df['Giá:'][df['Loại tin']=='Cho thuê'].unique()

array([], dtype=object)

In [18]:
df['Giá:'] = df['Giá:'].apply(lambda x: x.replace(',', '.'))

In [19]:
def clean_price(x, dien_tich):
    if 'ngàn /\xa0m2\xa0\xa0/\xa0tháng' in x:
        return float(x.split()[0]) * 1000*dien_tich
    elif 'triệu /\xa0tháng' in x:
        return float(x.split()[0]) * 1000000
    elif 'triệu /\xa0m2' in x:
        return float(x.split()[0]) * 1000000 * dien_tich 
    elif 'ngàn /\xa0m2' in x:
        return float(x.split()[0]) * 1000*dien_tich
    elif ' tỷ' in x:
        return float(x.split()[0]) * 1000000000
    elif ' triệu' in x:
        return float(x.split()[0]) * 1000000
    elif x == 'Thỏa thuận':
        return None  
    else:
        return x

In [20]:
df['Giá:'] = df.apply(lambda row: clean_price(row['Giá:'], row['Diện tích:']), axis=1)

In [21]:
df['Giá:']=df['Giá:'].astype(float)

# Giá/m2

In [22]:
df['Giá/m2']=df['Giá:']/df['Diện tích:']

In [23]:
df['Giá/m2']

0       9.160000e+07
1       6.249375e+07
2       2.166667e+07
3       3.130435e+07
4       7.460317e+07
            ...     
8037    5.555556e+07
8038    8.000000e+07
8039    3.550000e+07
8040    6.200000e+07
8041    8.771930e+07
Name: Giá/m2, Length: 8042, dtype: float64

# Hướng

In [24]:
df['Hướng'].unique()


array(['_', 'Tây Nam', 'Bắc', 'Đông', 'Đông Nam', 'Tây Bắc', 'Đông Bắc',
       'Tây', 'Nam'], dtype=object)

In [25]:
df['Hướng'] = df['Hướng'].apply(lambda x: np.nan if isinstance(x, str) and x == '_' else x)

# Phòng ăn

In [26]:
df['Phòng ăn'].unique()

array([nan, '---'], dtype=object)

In [27]:
df['Nhà bếp'].unique()

array([nan, '---'], dtype=object)

In [28]:
df['Sân thượng'].unique()

array([nan, '---'], dtype=object)

In [29]:
df['Chổ để xe hơi'].unique()

array([nan, '---'], dtype=object)

In [30]:
df['Chính chủ'].unique()

array(['---', nan], dtype=object)

In [31]:
df['Phòng ăn']=df['Phòng ăn'].fillna('Có').replace('---',np.nan)
df['Nhà bếp']=df['Nhà bếp'].fillna('Có').replace('---',np.nan)
df['Sân thượng']=df['Sân thượng'].fillna('Có').replace('---',np.nan)
df['Chổ để xe hơi']=df['Chổ để xe hơi'].fillna('Có').replace('---',np.nan)
df['Chính chủ']=df['Chính chủ'].fillna('Có').replace('---',np.nan)

# Đường trước nhà, Chiều ngang, Chiều dài

In [32]:
df['Đường trước nhà'].unique()

array(['30m', '7,5m', '3m', '15m', '5,5m', '5m', '6m', '10,m', '8m',
       '10m', '---', '33m', '11m', '75m', '5,1m', '20m', '7m', '40m',
       '9mm', '18m', '32m', '4m', '23m', '2,5m', '3,5m', '10,5m', '12m',
       '35m', '105m', '21m', '31m', '2m', '4,5m', '25m', '1m', '5m5m',
       '13m', '58m', '45m', '36m', '22m', '7m5m', '3m7m', '17m', '39m',
       '16m', '48m', '60m', '42m', '5mm', '4mm', '3,3m', '3,2m', '27m',
       '50m', '55m', '24m', '2m5m', '52m', '3m5m', '3mm', '|15m', '14m',
       '26m', '70m', '6,5m', '9m', '120m', '2,3m', '43m', '7,7m', '46m',
       '2,7m', '10mm', '3,7m', '3,8m', '9,5m', '5,6m', '5M5m', '7M5m',
       '253m', '44m', '34m', '1,8m'], dtype=object)

In [33]:
df['Chiều ngang'].unique()

array(['5m', '10m', '6m', '4m', '20m', '14m', '14,7m', '8m', '7m', '6,5m',
       '5,5m', '---', '4,5m', '75m', '30m', '9,4m', '7,5m', '15m', '9m',
       '25m', '8,2m', '9,6m', '9,55m', '5,2m', '13,2m', '5,4m', '6,8m',
       '8,5m', '4,54m', '4,3m', '7,4m', '4,85m', '11m', '3,7m', '4,07m',
       '5,1m', '18,15m', '12m', '5,6m', '6,3m', '6,7m', '7,6m', '13m',
       '100m', '9,5m', '4,6m', '4,4m', '8,3m', '8,1m', '7,8m', '6,56m',
       '3,8m', '7,2m', '3,55m', '80m', '18m', '5,3m', '18,50m', '24m',
       '27m', '0m', '41m', '33m', '11,5m', '3,6m', '715m', '5,7m', '82m',
       '8,6m', '7,1m', '17,34m', '3,5m', '4,2m', '22m', '85m', '3,1m',
       '4,1m', '17m', '36m', '12,5m', '50m', '19m', '9,2m', '4,75m',
       '40m', '3,53m', '16m', '15,5m', '8,8m', '32m', '11,9m', '400m',
       '23,5m', '31,5m', '4,7m', '8,7m', '6,1m', '23m', '13,5m', ',2m',
       '5,25m', '8,4m', '6,25m', '4,8m', '8,69m', '6,72m', '6m3m', '3,9m',
       '5,41m', '9,63m', '70m', '6,2m', '21m', '4,9m', '11,4m

In [34]:
df['Chiều dài'].unique()

array(['25m', '18m', '---', '24m', '16m', '11m', '12m', '19m', '15m',
       '20m', '35m', '21m', '23m', '17m', '225m', '38m', '40m', '26m',
       '17,5m', '22m', '30m', '14m', '32m', '19,8m', '90m', '14,2m',
       '22,5m', '23,5m', '24,5m', '14,5m', '22,6m', '15,6m', '6,6m', '7m',
       '10m', '18,5m', '16,5m', '21,5m', '21,7m', '13m', '18,4m', '29m',
       '16,3m', '16,8m', '8m', '19,5m', '12,5m', '65m', '17,2m', '18,6m',
       '29,71m', '42m', '18,2m', '16,2m', '4,5m', '9m', '160m', '23,3m',
       '20,3m', '18,3m', '20,7m', '0m', '4m', '7,9m', '5m', '31m',
       '19,3m', '36m', '100m', '27m', '132m', '9,55m', '10,4m', '28m',
       '6m', '95m', '60m', '53m', '13,5m', '25,2m', '20,5m', '25,5m',
       '15,5m', '21,3m', '33m', '41,5m', '2000m', '26,5m', '14,6m',
       '12,3m', '21,9m', '22,8m', '27,8m', '21,2m', '8,5m', '10,5m',
       '12,2m', '11,3m', '11,6m', '23,75m', '13,3m', '19,4m', '14,25m',
       '23,2m', '15,75m', '37m', '18,8m', '15,8m', '88m', '17,4m',
       '24,

In [35]:
def process_width(text):
    if isinstance(text,str):
        x=text.lower().replace('mm', 'm').replace(',', '.').replace('m','.').replace('+','').replace('---','').replace('|','').replace('/','.').replace('-','.')
        x = re.sub(r'\.\Z', '', x)
        x = re.sub(r'^[^0-9]+', '', x)
        return x
    else:
        return ''

In [36]:
df['Đường trước nhà']= df['Đường trước nhà'].apply(lambda x: process_width(x))
df['Chiều ngang']= df['Chiều ngang'].apply(lambda x: process_width(x))
df['Chiều dài']= df['Chiều dài'].apply(lambda x: process_width(x))

In [37]:
df['Đường trước nhà'] = df['Đường trước nhà'].apply(replace_empty_with_nan)
df['Chiều ngang'] = df['Chiều ngang'].apply(replace_empty_with_nan)
df['Chiều dài'] = df['Chiều dài'].apply(replace_empty_with_nan)

In [38]:
df['Đường trước nhà']=df['Đường trước nhà'].astype(float)
df['Chiều ngang']=df['Chiều ngang'].astype(float)
df['Chiều dài']=df['Chiều dài'].astype(float)

# Loại bất động sản

In [39]:
df['Loại BDS'].unique()

array(['Nhà mặt tiền', 'Nhà trong hẻm', 'Nhà hàng, khách sạn',
       'Đất thổ cư, đất ở', 'Phòng trọ, nhà trọ', 'Căn hộ chung cư',
       'Biệt thự, nhà liền kề', 'Đất nền, liền kề, đất dự án',
       'Kho, xưởng', 'Văn phòng', 'Đất nông, lâm nghiệp', 'Mặt bằng',
       'Các loại khác', 'Shop, kiot, quán'], dtype=object)

# Pháp lý

In [40]:
df['Pháp lý'].unique()

array(['Giấy tờ hợp lệ', 'Sổ hồng/ Sổ đỏ', '---', 'Giấy phép XD'],
      dtype=object)

In [41]:
df['Pháp lý'] = df['Pháp lý'].apply(lambda x: np.nan if isinstance(x, str) and x == '---' else x)

# Số lầu, số phòng ngủ

In [42]:
df['Số lầu'].unique()

array(['4', '1', '3', '10', '2', '5', '6', '---', '27', '33', '11', '21',
       '19', '7', '12', '15', '16', '25', '8', '160', '9', '13', '26',
       '17', '20', '23', '18', '14', '35', '24', '22', '40', '37', '30',
       '28'], dtype=object)

In [43]:
df['Số phòng ngủ'].unique()

array(['9', '1', '3', '50', '4', '6', '7', '---', '2', '5', '15', '270',
       '13', '23', '60', '22', '200', '110', '10', '21', '12', '16', '26',
       '8', '18', '56', '19', '80', '52', '98', '11', '36', '27', '24',
       '150', '264', '25', '78', '20', '81', '100', '32', '190', '34',
       '28', '65', '42', '35', '17', '161', '48', '75', '40', '105', '14',
       '94', '33', '90', '70', '49', '30', '41', '92', '51', '77', '96',
       '73', '111', '125', '55', '31', '47', '45', '130', '300', '108',
       '37', '104', '102', '72', '62', '54', '53', '120', '126', '95',
       '133', '46', '86', '38', '67', '43'], dtype=object)

In [44]:
df['Số lầu'] = df['Số lầu'].apply(lambda x: np.nan if isinstance(x, str) and x == '---' else x)
df['Số phòng ngủ'] = df['Số phòng ngủ'].apply(lambda x: np.nan if isinstance(x, str) and x == '---' else x)

In [45]:
df['Số lầu'] = pd.to_numeric(df['Số lầu'], errors='coerce')
df['Số phòng ngủ'] = pd.to_numeric(df['Số phòng ngủ'], errors='coerce')

In [46]:
# df['Số lầu']=df['Số lầu'].astype(int)
# df['Số phòng ngủ']=df['Số phòng ngủ'].astype(int)

# Phone

In [47]:
# df['phone'].unique()

In [48]:
df['phone']=df['phone'].apply(lambda x: x.replace('.',' ').replace("84", "0", 1))

# Địa chỉ

In [49]:
df['Địa chỉ'].unique()

array(['Địa chỉ tài sản: Đường Nguyễn Tất Thành, Phường Xuân Hà, Quận Thanh Khê, Đà Nẵng',
       'Địa chỉ tài sản: Đường Nguyễn Phong Sắc, Phường Khuê Trung, Quận Cẩm Lệ, Đà Nẵng',
       'Địa chỉ tài sản: Đường Tô Hiệu, Phường Hòa Minh, Quận Liên Chiểu, Đà Nẵng',
       ...,
       'Địa chỉ tài sản: Đường Bàu Cầu 15, Phường Hòa Xuân, Quận Cẩm Lệ, Đà Nẵng',
       'Địa chỉ tài sản: Võ Quí Huân Đường Võ Quí Huân, Phường Hòa Hải, Quận Ngũ Hành Sơn, Đà Nẵng',
       'Địa chỉ tài sản: Trung Lương 11 Trung Lương 11, Phường Hòa Xuân, Quận Cẩm Lệ, Đà Nẵng'],
      dtype=object)

In [50]:
df['Địa chỉ']=df['Địa chỉ'].apply(lambda x: x.replace('Địa chỉ tài sản: ',''))

# Tên người dùng

In [51]:
df['Liên hệ'].unique()

array(['Trần Trung Hậu', 'Hiền Hiền', 'Quốc', 'Nguyễn Ái', 'Công Minh',
       'Trần Viết Phúc', 'Lê Minh Đức', 'Nguyễn khăc Dũng',
       'Phạm ngọc Nhật', 'Võ Hiệu', 'Trần Xuân Thắng', 'Nguyễn Hoàng Duy',
       'CHÍNH CHỦ', 'Thanh Loan', 'Võ Văn Bảo', 'Vũ Thị Hà', 'Mỹ Dung',
       'lê thu trang', 'Ngọc Oanh', 'Võ Kim Liên', 'Sơn Chấn',
       'Phú Nguyễn', 'Hà Văn Hợi', 'Nguyễn Tấn Luân', 'Thanh Nga',
       'Phan Thanh Chương', 'Quang Diep', 'Mr. Lực', 'Nguyễn Trung Dũng',
       'Minh', 'Ngọc Hùng & Ngọc Oanh', 'CHÂU HOÀNG', 'lê thanh tín',
       'Linh', 'Nguyễn Ngọc Hải', 'Zũ Land', 'Hoàng Anh', 'Land',
       'Trương công Lành', 'Nguyễn Hữu Tín', 'Nguyễn Thị Thủy',
       'Vũ Kim Dung', 'Nguyễn Nhật Lam', 'Trần Thị Quốc Thái',
       'Đặng Bình Phi Hoàng', 'Hiếu Anh', 'Lê Thị Lệ Huyền',
       'Thân Hoàng Tuấn', 'Phú Mẫn', 'Phan Thanh', 'Thân Tuấn',
       'Tuấn Kiệt', 'lê ngọc sỹ', 'Anh Dũng', 'Nguyễn Trung Tín',
       'Nguyễn Hùng Anh', 'Hà Duy Thịnh', 'nguyễn ngọc vũ'

In [52]:
df['Liên hệ']=df['Liên hệ'].str.title()

In [53]:
df['Liên hệ'].unique()

array(['Trần Trung Hậu', 'Hiền Hiền', 'Quốc', 'Nguyễn Ái', 'Công Minh',
       'TrầN ViếT PhúC', 'Lê Minh Đức', 'Nguyễn Khăc Dũng',
       'Phạm Ngọc Nhật', 'Võ Hiệu', 'Trần Xuân Thắng', 'Nguyễn Hoàng Duy',
       'Chính Chủ', 'Thanh Loan', 'Võ Văn BảO', 'Vũ Thị Hà', 'Mỹ Dung',
       'Lê Thu Trang', 'Ngọc Oanh', 'Võ Kim Liên', 'Sơn Chấn',
       'Phú Nguyễn', 'Hà Văn Hợi', 'Nguyễn Tấn Luân', 'Thanh Nga',
       'Phan Thanh Chương', 'Quang Diep', 'Mr. Lực', 'Nguyễn Trung Dũng',
       'Minh', 'Ngọc Hùng & Ngọc Oanh', 'Châu Hoàng', 'Lê Thanh Tín',
       'Linh', 'Nguyễn Ngọc Hải', 'Zũ Land', 'Hoàng Anh', 'Land',
       'Trương Công Lành', 'Nguyễn Hữu Tín', 'Nguyễn Thị Thủy',
       'Vũ Kim Dung', 'Nguyễn Nhật Lam', 'Trần Thị Quốc Thái',
       'Đặng Bình Phi Hoàng', 'Hiếu Anh', 'Lê Thị Lệ Huyền',
       'Thân Hoàng Tuấn', 'Phú Mẫn', 'Phan Thanh', 'Thân Tuấn',
       'Tuấn Kiệt', 'Lê Ngọc Sỹ', 'Anh Dũng', 'Nguyễn Trung Tín',
       'Nguyễn Hùng Anh', 'Hà Duy Thịnh', 'Nguyễn Ngọc Vũ'

# Mô tả

In [54]:
df['Mô tả'].unique()

array(['Nhà đẹp, view biển, 4 tầng, 9 phòng ngủ, khu vực an. ninh, thích hợp cho việc kinh doanh khách sạn, nhà nghỉ.Diện Tích 125m2 (5x25)Vị trí nằm Sát Công Viên Nguyễn Tất Thành Hà Huy Tập. Khu kinh doanh nhà hàng, khách sạn sầm uất... View biển rất đẹp.-- Đường trước nhà: 30 m, vỉa hè: 10 m.-Giá bán 11,5 Tỷ Còn Thương lượngnhà mới xây kiên cốThu nhập 20tr/1thangLiên Hệ E hậu',
       '+ Bán lô góc 3 mặt tiền 3 đường 7m5 Nguyễn Phong Sắc, phường Khuê Trung, quận Cẩm Lệ, Đà Nẵng.+ Diện tích: 160m2, ngang (9m6x17,9m). Đường 7m5, lề 4m. Hướng Đông + Bắc.+ Vị trí nằm khu vực 2 mặt tiền đều là đường 7m5 thông thoáng, kẹp đường bê tông 6m bên hông, thành thế 3 mặt tiền cực thông thoáng. Ngay khu Xô viết Nghệ tĩnh tập trung hành chính công và Nguyễn Hữu Thọ khu văn phòng+ Gia đình cần tiền mặt bán nhanh 10 tỷLàm Việc Chính Chủ Liên Hệ E Hậu',
       '🌺🌺Nhà sân vườn biệt thự 3 tầng mới xây, đường Tô Hiệu gần Bến Xe TT Đà Nẵng- Diện tích đất thực tế : 150m- Diện tích đất trong sổ : 122m- Bon

# Thuộc dự án

In [55]:
df['Thuộc dự án'].unique()

array([nan,
       'Căn hộ chung cư Sun Cosmo Residence Đà Nẵng (xem chi tiết dự án)',
       'Khu biệt thự Euro Village 2 (xem chi tiết dự án)',
       'Khu đô thị mới Nam Việt Á (Nam Cầu Tuyên Sơn) (xem chi tiết dự án)',
       'Khu đô thị mới FPT City Đà Nẵng (xem chi tiết dự án)',
       'Căn hộ chung cư FPT Plaza 2 (xem chi tiết dự án)',
       'Khu dân cư 387 (xem chi tiết dự án)',
       'Khu đô thị mới B.Ocean (xem chi tiết dự án)',
       'Căn hộ chung cư Nhà ở xã hội Khu công nghiệp Hòa Khánh (xem chi tiết dự án)',
       'Khu biệt thự Euro village Đà Nẵng (xem chi tiết dự án)',
       'Căn hộ chung cư FPT Plaza (xem chi tiết dự án)',
       'Khu đô thị mới Khu đô thị sinh thái Hoà Xuân (xem chi tiết dự án)',
       'Căn hộ chung cư F.Home (xem chi tiết dự án)',
       'Căn hộ chung cư Blue House (xem chi tiết dự án)',
       'Căn hộ chung cư Nest Home (xem chi tiết dự án)',
       'Khu đô thị mới Phương Trang - Vịnh Đà Nẵng (Marina Bay Luxury) (xem chi tiết dự án)',
       '

In [56]:
df['Thuộc dự án']=df['Thuộc dự án'].apply(lambda x: str(x).replace(' (xem chi tiết dự án)',''))

# Rename columns

In [57]:
df.columns

Index(['post_id', 'Loại tin', 'Tiêu đề', 'Mô tả', 'Giá:', 'Diện tích:',
       'Địa chỉ', 'Mã tin', 'Hướng', 'Phòng ăn', 'Đường trước nhà', 'Nhà bếp',
       'Loại BDS', 'Pháp lý', 'Sân thượng', 'Chiều ngang', 'Số lầu',
       'Chổ để xe hơi', 'Chiều dài', 'Số phòng ngủ', 'Chính chủ', 'URL',
       'date', 'Liên hệ', 'phone', 'Thuộc dự án', 'Giá/m2'],
      dtype='object')

In [58]:
df=df.rename(columns={'Hướng':'Hướng nhà','Liên hệ':'Tên người dùng','Diện tích:':'Diện tích','Giá:':'Giá','phone':'Liên hệ','date':'Ngày crawl'})

# Save data

In [59]:
df

post_id Loại tin                                            Tiêu đề  \
0     13131558  Mua bán  Bán Nhà Đẹp VIEW Biển NGUYỄN TẤT THÀNH 4 Tầng ...   
1     13456587  Mua bán  Góc 3 Mặt Tiền Nguyễn Phong Sắc 3 Đường 7m5 VỊ...   
2     13467139  Mua bán   BÁN BIỆT THỰ SÂN VƯỜN 150M2 KIỆT TÔ HIỆU lh Hiền   
3     12734876  Mua bán  Bán khách sạn 2mt Đống Đa, Lý Tự Trọng, dtd: 2...   
4     13472701  Mua bán  Lê Thị Xuyến đường 5m5 Dt= 63m2 kẹp kiệt 2 tần...   
...        ...      ...                                                ...   
8037  13547701  Mua bán  Bán gấp lô đất sát biển MT đường Nguyễn Trọng ...   
8038  13233191  Mua bán  💥💥 DANH SÁCH CÁC TOÀ CĂN HỘ BIỂN ĐÀ NẴNG – DÒN...   
8039  13546882  Mua bán  Bán đất đường lê ấm hoà xuân cẩm lệ. Hướng đôn...   
8040  13535617  Mua bán  ❌ Cần Bán Nhà 2 Tầng Nguyễn chí Diễu - DT 75m ...   
8041  12815424  Mua bán  BÁN GẤP NHÀ 3 TẦNG. MẶT TIỀN LÊ TRỌNG TẤN- CẨM...   

                                                  Mô tả           Giá  \
0     Nhà đẹp, view biển, 4 tầng, 9 phòng ngủ, khu v...  1.145000e+10   
1     + Bán lô góc 3 mặt tiền 3 đường 7m5 Nguyễn Pho...  9.999000e+09   
2     🌺🌺Nhà sân vườn biệt thự 3 tầng mới xây, đường ...  3.250000e+09   
3     Bán toà nhà khách sạn hai mặt tiền Đống Đa,Lý ...  7.200000e+10   
4     Hàng hiếm.Lê Thị Xuyến đường 5m5 Dt= 63m2 kẹp ...  4.700000e+09   
...                                                 ...           ...   
8037  Bán lô đất biển mặt tiền đường Nguyễn Trọng Ng...  5.000000e+09   
8038  💥💥 DANH SÁCH CÁC TOÀ CĂN HỘ BIỂN ĐÀ NẴNG – DÒN...  1.200000e+10   
8039  Bán đất đường Lê Ấm, hòa xuân - Cẩm Lệ- Diện t...  3.550000e+09   
8040  Cần Bán Nhà 2 Tầng NGUYỄN CHÍ DIỄU Đường 7m5 -...  4.650000e+09   
8041  ✅ Vị trí : Mặt tiền Lê Trọng Tấn kinh doanh sầ...  5.000000e+09   

      Diện tích                                            Địa chỉ    Mã tin  \
0         125.0  Đường Nguyễn Tất Thành, Phường Xuân Hà, Quận T...  13131558   
1         160.0  Đường Nguyễn Phong Sắc, Phường Khuê Trung, Quậ...  13456587   
2         150.0  Đường Tô Hiệu, Phường Hòa Minh, Quận Liên Chiể...  13467139   
3        2300.0  191 Đường Đống Đa, Phường Thạch Thang, Quận Hả...  12734876   
4          63.0  Đường Lê Thị Xuyến, Phường Xuân Hà, Quận Thanh...  13472701   
...         ...                                                ...       ...   
8037       90.0  Đường Nguyễn Trọng Nghĩa, Phường Mân Thái, Quậ...  13547701   
8038      150.0  Đường Nguyễn Văn Thoại, Phường An Hải Đông, Qu...  13233191   
8039      100.0  Đường Lê Ấm, Phường Hòa Xuân, Quận Cẩm Lệ, Đà ...  13546882   
8040       75.0  Đường Nguyễn Chí Diễu, Phường An Hải Bắc, Quận...  13535617   
8041       57.0  Đường Lê Trọng Tấn, Phường Hòa Phát, Quận Cẩm ...  12815424   

     Hướng nhà Phòng ăn  ...  Chổ để xe hơi Chiều dài Số phòng ngủ Chính chủ  \
0          NaN       Có  ...             Có      25.0          9.0       NaN   
1          NaN       Có  ...             Có      18.0          1.0       NaN   
2          NaN       Có  ...            NaN       NaN          3.0       NaN   
3      Tây Nam      NaN  ...            NaN      24.0         50.0       NaN   
4          Bắc       Có  ...             Có      16.0          3.0       NaN   
...        ...      ...  ...            ...       ...          ...       ...   
8037      Đông      NaN  ...            NaN      18.0          NaN       NaN   
8038      Đông      NaN  ...            NaN      30.0          NaN       NaN   
8039  Đông Nam      NaN  ...            NaN      20.0          NaN       NaN   
8040       NaN      NaN  ...            NaN       NaN          3.0       NaN   
8041       NaN       Có  ...             Có      10.0          3.0       NaN   

                                                    URL  Ngày crawl  \
0     https://alonhadat.com.vn//ban-nha-dep-view-bie...  2023-10-02   
1     https://alonhadat.com.vn//ban-lo-goc-3-mat-tie...  2023-10-02   
2     https://alonhadat.com.vn//ban-biet-thu-san-vuo...  2

In [61]:
df.to_excel('alo.xlsx')
df.to_csv('alo.csv')